"use strict";

/**
 * Bakes the built app and the server into a single self-contained file.
 *
 *   node build.js            bundle everything, fonts included
 *   node build.js --no-fonts leave the ~14MB of fonts out
 *
 * Output: serverBundle.js, runnable with a bare `node serverBundle.js` from
 * anywhere, with no node_modules and no app/dist alongside it.
 */

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const zlib = require("zlib");

const esbuild = require("esbuild");

const DIST = path.resolve(__dirname, "..", "app", "dist");
const GENERATED = path.join(__dirname, "assets.generated.js");
const OUTFILE = path.join(__dirname, "serverBundle.js");

const skipFonts = process.argv.includes("--no-fonts");

/** Compressing an already-compressed format just burns CPU for nothing. */
const INCOMPRESSIBLE = new Set([
  ".woff",
  ".woff2",
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".webp",
  ".ico",
]);

const walk = (dir) => {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...walk(full));
    } else if (entry.isFile()) {
      out.push(full);
    }
  }
  return out;
};

const human = (bytes) => `${(bytes / 1024 / 1024).toFixed(1)}MB`;

const main = async () => {
  if (!fs.existsSync(path.join(DIST, "index.html"))) {
    console.error(
      `No build at ${DIST}\nRun "npm run build" in the app folder first.`,
    );
    process.exit(1);
  }

  const files = walk(DIST).filter((file) => {
    if (!skipFonts) {
      return true;
    }
    const rel = path.relative(DIST, file).split(path.sep).join("/");
    return !rel.startsWith("fonts/");
  });

  const entries = [];
  let rawTotal = 0;
  let storedTotal = 0;

  for (const file of files) {
    const rel = path.relative(DIST, file).split(path.sep).join("/");
    const raw = fs.readFileSync(file);
    const etag = `"${crypto.createHash("sha1").update(raw).digest("hex").slice(0, 16)}"`;

    let stored = raw;
    let encoding = "";
    if (!INCOMPRESSIBLE.has(path.extname(rel).toLowerCase())) {
      const gz = zlib.gzipSync(raw, { level: 9 });
      // Only worth it if it actually saves something meaningful.
      if (gz.length < raw.length * 0.9) {
        stored = gz;
        encoding = "gzip";
      }
    }

    rawTotal += raw.length;
    storedTotal += stored.length;
    entries.push(
      `${JSON.stringify(rel)}:[${JSON.stringify(stored.toString("base64"))},` +
        `${JSON.stringify(encoding)},${raw.length},${JSON.stringify(etag)}]`,
    );
  }

  fs.writeFileSync(
    GENERATED,
    `// Generated by build.js - do not edit.\nmodule.exports={${entries.join(",")}};\n`,
  );

  try {
    await esbuild.build({
      entryPoints: [path.join(__dirname, "server.js")],
      outfile: OUTFILE,
      bundle: true,
      platform: "node",
      target: "node18",
      format: "cjs",
      // The asset map is one enormous string table; minifying it gains nothing
      // and makes the output painful to inspect.
      minify: false,
      legalComments: "none",
      banner: {
        js: "// Excalihere - self-contained server bundle. Run: node serverBundle.js",
      },
    });
  } finally {
    // The generated module is a build artifact; it has served its purpose once
    // esbuild has inlined it.
    fs.rmSync(GENERATED, { force: true });
  }

  const outSize = fs.statSync(OUTFILE).size;
  console.log(`Bundled ${files.length} files${skipFonts ? " (fonts excluded)" : ""}`);
  console.log(`  app assets:  ${human(rawTotal)} raw -> ${human(storedTotal)} stored`);
  console.log(`  serverBundle.js: ${human(outSize)}`);
  console.log(`\nRun it with:  node ${path.relative(process.cwd(), OUTFILE)}`);
};

main().catch((error) => {
  fs.rmSync(GENERATED, { force: true });
  console.error(error);
  process.exit(1);
});
